title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome test of the awesomeness that is GitHub Pages. 

# social links
twitter_username: desertmonkey
github_username:  desertmonkey

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
